name: Continuous Integration

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
          registry-url: https://registry.yarnpkg.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Linting Projects
        run: yarn lint
      - name: Building Projects
        run: yarn build
